#!/bin/bash
clear
echo -e "==========================================="
echo -e "        AutoScript VPN By Geo Project        "
echo -e "==========================================="
echo -e "This Script Is Using 4 Cores"
echo -e "Services That Available :"
echo -e "XRay VMess"
echo -e "XRay VLess"
echo -e "XRay Trojan"
echo -e "XRay XTLS"
echo -e "V2ray VMess"
echo -e "V2Ray VLess"
echo -e "V2Ray Trojan"
echo -e "Trojan GO"
echo -e "Stunnel5"
echo -e "Websocket SSH"
echo -e "ShadowsocksR"
echo -e "Shadowsocks"
echo -e "OHP OPenVPN & SSH"
echo -e "Wireguard"
echo -e "Webmin"
echo -e "==========================================="
echo -e "         Telegram : t.me/sampiiiiu         "
echo -e "==========================================="
